### PR TITLE
Add Azure Pipelines GitVersion task configuration and usage examples

### LINKED ISSUE #236: Missing documentation for available configuration for the Azure pipelines task
Hi,

I'm having a hard time finding an overview of the available configuration for the Azure pipelines task for gitversion. There is one example: https://github.com/GitTools/actions/blob/master/docs/examples/azure/gitversion/index.md 

Is there any documentation that I have missed? If not, it would be great if an overview of available configuration for this task. Nothing fancy is required - but a list of all inputs would be awesome.

Thanks :)

### PR DESCRIPTION
**Pull request by chris-codeflow**
- Added configuration and usage examples for the **Setup GitVersion** and **Execute GitVersion** tasks in Azure Pipelines.
- Updated and added new screenshots for the Azure Pipelines marketplace extension (VSIX package).
- Changed the VSIX package to include images (addressable from the **overview.md**) in the package itself, instead of using a link to GitHub user content.

Closes #236.

All examples have been verified in real Azure Pipelines runs.

### CODE REVIEW

**Comment by arturcic** [comment]
@chris-codeflow thank you very much for updating the docs for Azure pipelines task. I like the samples, Do you mind if you add similar docs for the GitHub actions so that we cover them as well? As basically they are the same just the syntax is a bit different

**Comment by chris-codeflow** [comment]
Hello @arturcic.  No problem.  I haven't used GitHub actions before, so I don't feel confident in creating examples.  If you could send me a link or some info for using GitHub actions, I can have a look and try it out.

**Comment by arturcic** [comment]
@chris-codeflow I guess you can start with this intro https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions and then you can check the usage of the actions here https://github.com/GitTools/actions/blob/master/gitversion/execute/action.yml and https://github.com/GitTools/actions/blob/master/gitversion/setup/action.yml and usage of the actions in this repo https://github.com/GitTools/actions/blob/a5bd3bccabbc15a9ecc9cd7287426788bba37508/.github/workflows/ci.yml#L30

**Comment by chris-codeflow** [comment]
@arturcic Thanks for the GitHub Actions links.  I've had a cursory look at some of the docs and the syntax looks similar to Azure Pipelines, especially after reading [Migrating from Azure Pipelines to GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-azure-pipelines-to-github-actions) - I can see where the confusion over the `steps` syntax comes from now in the issues raised for the Azure Pipelines task.

I will create a branch to migrate my Azure Pipelines examples to GitHub Actions and try them in my own fork.

Can we merge this PR as the changes I've made are specifically for Azure Pipelines (and so don't affect the GitHub Actions) and I can do the GitHub Actions work under a different PR?

**Comment by arturcic** [comment]
@chris-codeflow works for me

**Comment by arturcic** [comment]
Merged, waiting for the other PR and then we can release so that we get the new vsix extension with the updated images

**Comment by chris-codeflow** [comment]
This PR also closes #209.

**Pull request merged**
