### PR TITLE
Remove buildserver output argument from GitVersion tool as it's duplicating the actions behavior

### PR DESCRIPTION
**Pull request by arturcic**
Removed the '/output buildserver' argument from the `gitversion` tool execution. Updated all related unit tests to reflect this change, ensuring consistency and correctness across different configurations.

### CODE REVIEW

**Comment by WilliBarankin** [comment]
Looks like this change completely brakes Azure pipeline. Rolling back to version 3.0.3 fix the issue

**Comment by Nidolai** [comment]
Brakes Azure pipelines for me as well.

**Comment by davidkeaveny** [comment]
I'm using the Azure DevOps GitVersion task, and this change from 3.0.3 to 3.0.4 has broken my pipelines, as it's not now setting `$(Build.BuildNumber)` - what setting do I need to update to restore normal functionality?

If my pipeline YAML includes the following:
```yaml
stages:
- stage: Packaging
  jobs:
  - job: buildAndPackage
    steps:
    - checkout: self
      fetchDepth: '0'
    - task: gitversion/setup@3
      inputs:
        versionSpec: '5.10.x'
    - task: gitversion/execute@3
      inputs:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'
```

Previous builds, which picked up v3.0.3 would produce the following output:
```
GitVersion executed successfully
Async Command Start: Update Build Number
Update build number to 1.15.0-unstable.90 for build 125299
Async Command End: Update Build Number
Finishing: Calculate version number
```

But today's builds, picking up v3.0.4, produce the following output:
```
GitVersion executed successfully
Finishing: Calculate version number
```

I can work around this by explicitly setting the GitVersion tool number in my pipeline YAML to v3.0.3, then my builds pass again, so it's definitely the v3.0.4 build that is breaking things for me.

**Comment by arturcic** [comment]
@davidkeaveny that's a valid bug, I will fix it as part of the #1389

**Pull request merged**
