### PR TITLE
GH-245 Update build-agent arguments handling

### PR DESCRIPTION
**Pull request by Leosori**
This should fix the argument handling, but I have no way to test this

And someone has to compile this into JavaScript of course :-)

### CODE REVIEW

**Comment by GSDragoon** [comment]
Not sure if this is a good test, but targeting your commit for the action version fixed the issue for me. Look at the `Install GitVersion`, `Use GitVersion` and `Run echo "Major 1"` tasks.

[Your Commit](https://github.com/GSDragoon/RadeonSoftwareSlimmer/runs/1383489002?check_suite_focus=true) Ignore the other failure, .NET 5 isn't available on agents yet.
[0.9.4](https://github.com/GSDragoon/RadeonSoftwareSlimmer/runs/1383379991?check_suite_focus=true) It was still using GitVersion with the set-env issue, but is unrelated.

**Comment by arturcic** [comment]
> And someone has to compile this into JavaScript of course :-)

@Leosori you can build it yourself by running `npm run build` and commit the changes

**Comment by arturcic** [comment]
@Leosori you need to also run `npm run format`

**Comment by Leosori** [comment]
@arturcic ok, code is now pretty :-)

I had to change the handling of arguments from my initial fix. While it did work most of the time, it introduced a new bug if, for example, the path to the config file contains spaces. Now the default parameters are handled like before but only the additional arguments are passed differently to the tool runners. Therefore the additional arguments are now an optional/default string parameter on the exec methods.

**Comment by arturcic** [comment]
@Leosori can you check this different implementation? https://github.com/GitTools/actions/pull/250

**Comment by arturcic** [comment]
@Leosori I will close this one in favor of #250. Thank you for the input needed for fixing this issue

**Pull request closed without merging**
