### PR TITLE
Add private repo documentation

### LINKED ISSUE #9: Fetch and Create Reflog don't work for private repositories (Unauthorized)
I found that the directions as documented don't work for private repositories.

When one creates an action in a private repository following the instructions,  they'll find that the action fails or hangs when it tries to run 'git fetch --tags'.  With an ubuntu action the error reads: 'fatal: could not read Username for 'https://github.com': No such device or address'.  With a windows action the action hangs after it opens credential manager.

It appears that the [actions/checkout](https://github.com/actions/checkout) action resets git configuration after checkout so the credentials aren't available to the 'git fetch --tags' and 'git branch --create-reflog master origin/master' commands.  https://github.com/actions/checkout/blob/5881116d181dc80f3ed5f395296a5579ee6fc6a4/src/git-source-provider.ts#L146

I recommend adding another line to the 'Fetch tags and master for GitVersion' step in the documentation to add credentials for private repositories.  The following command is working well for me:
```yaml
git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
```

```yaml
    steps:
    - name: Checkout
    uses: actions/checkout@v1
    - name: Fetch tags and master for GitVersion
    run: |          
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} # creds needed for private repos
        git fetch --tags
        git branch --create-reflog master origin/master
```

### PR DESCRIPTION
**Pull request by bofirial**
Add git credentials to documentation to support private repositories

Fixes #9

### CODE REVIEW

**Comment by bofirial** [comment]
Let me know if there is anything else I can help with.  I'm new to open source so if I've done anything incorrectly just let me know and I'll be happy to correct the issue.

**Comment by arturcic** [comment]
@bofirial to be honest I would prefer to have the info for private repos as separate section if possible, as the step for the public repos is not needed. Can you add a separate section that says that if you have private repo, you need to run the script before running the action

**Comment by bofirial** [comment]
@arturcic No problem.  I moved it to a private repo section and removed the command from the 2 previous examples.

Happy to tweak further if you have any other feedback.

**Comment by arturcic** [comment]
@bofirial thank you for the contribution! :+1:

**Pull request merged**
