### PR TITLE
Allow DOTNET_ROOT to be based on an actual file

### PR DESCRIPTION
**Pull request by Breederveld**
Note I haven't been able to test these changes.
Some input on how this can be achieved locally would be appreciated.

### CODE REVIEW

**Comment by arturcic** [comment]
@Breederveld Thanks for the PR, I agree currently the only way I test the code is by dog-fooding it to the CI. Basically I run the GitVersion task tool from the sources and if it builds it kind of works. But we need tests to be added

**Comment by arturcic** [comment]
thank you so much for your contributions 👍 @Breederveld

**Comment by Breederveld** [comment]
Happy to help, now crossing my fingers to see if it works 👍

**Comment by arturcic** [comment]
In few minutes you should be able to use version v0.9.1. Please use [this](https://marketplace.visualstudio.com/items?itemName=gittools.gittools) extension. If you already had it installed in the organization, please remove it before installation as it is caching the older one

**Comment by arturcic** [comment]
@Breederveld can you confirm it has solved the issue for you?

**Comment by Breederveld** [comment]
The issue is solved, but I'm getting a new one, do you know if this could be related? The DOTNET_ROOT env var is set ok.
----
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - No frameworks were found.

**Comment by arturcic** [comment]
Yes, it could be

**Comment by Breederveld** [comment]
Oh, sorry nevermind, I was multitasking too much here.
The PR solved the issue; the installer is working fine now!
I now get this issue with the execute step, but that is unrelated to this issue, so case closed

**Pull request merged**
