### PR TITLE
Fix invalid dependency on updateAssemblyInfoFilename input

### PR DESCRIPTION
**Pull request by chris-codeflow**
Fixed invalid dependency on `updateAssemblyInfoFilename` input.

Changed `GitVersionTool.getArguments` to check and use the `updateAssemblyInfoFilename` input string only if it's not empty.  This allows the execute task users to use the `updateAssemblyInfo` input in isolation, resulting in the **GitVersion** tool's default behaviour of recursively searching for and updating all 'AssemblyInfo.cs' files in the Git repository.

Fixes issue #125.

### CODE REVIEW

**Comment by chris-codeflow** [comment]
Hello @arturcic.  Bug fix PR ready for review.

**Comment by chris-codeflow** [comment]
Please can you 'squash commit' this PR (when complete) to avoid all the 'merge' commits.  I will sort my fork out to avoid this in the future.

**Review by asbjornu — APPROVED** [review]

**Review by arturcic — APPROVED** [review]

**Comment by arturcic** [comment]
@chris-codeflow thank you so much for your contributions 👍

**Comment by chris-codeflow** [comment]
Thanks @asbjornu and @arturcic for completing the PR review.

**Pull request merged**
