### PR TITLE
Update GitHub actions usage documentation

### PR DESCRIPTION
**Pull request by roryprimrose**

### CODE REVIEW

**Comment by roryprimrose** [comment]
Related to #252

**Comment by arturcic** [comment]
Do you mind updating the samples for azure as well?

**Comment by roryprimrose** [comment]
Done. I've assumed that it should be just `'5.x'`

**Review by arturcic — APPROVED** [review]

**Comment by arturcic** [comment]
@roryprimrose thank you so much for your contributions 👍

**Pull request merged**
