### PR TITLE
Reflect most recent version also in README.md

### PR DESCRIPTION
**Pull request by koppor**

### CODE REVIEW

**Comment by arturcic** [comment]
can you also update the doc examples? https://github.com/GitTools/actions/tree/master/docs/examples

**Comment by koppor** [comment]
Done.

Also added a link to each of the tool in the first sentence in README.md

**Comment by arturcic** [comment]
Looks good to me, do you mind updating the azure examples as well? looks like only the versionSpec is needed

**Comment by arturcic** [comment]
Do you mind updating the GitReleaseManager version as well? To have everything up to date

**Comment by koppor** [comment]
As far as I understood, Azure does not need full versions. Azure is "pinned" to the major version. `@0` means that all of `v0.x` is great 🎉. See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions

Did the other wish in 35f9dda

**Comment by arturcic** [comment]
@koppor  thank you so much for your contributions and your time 👍

**Pull request merged**
