### PR TITLE
export environment variables to github actions

### PR DESCRIPTION
**Pull request by david-driscoll**
We found a way to export to environment variables similar to how appveyor/travis/azure pipelines works.  

https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

Figured it made sense to add this as a PR instead of just tacking it on after each call to the action!

Co-authored-by: rlittlesii <6969701+RLittlesII@users.noreply.github.com>

### CODE REVIEW

**Comment by arturcic** [comment]
@david-driscoll wouldn't it be better to have a common approach for both azure and github extensions? maybe we should set it here https://github.com/GitTools/actions/blob/6dfe4060888153772a0c0e233e6fe4ae46099fd5/src/tools/gitversion/tool.ts#L118?

**Comment by david-driscoll** [comment]
@arturcic Azure Devops will set the environment variable when you call `setVariable` however this is not the case for GitHub Actions `setOutput`.  Azure Devops doesn't really have a mirror to `setOutput` for specific tasks.

Also this might mean that azure devops part isn't prefixing the variables with `GitVersion.` like things had been in the past.

**Comment by arturcic** [comment]
I think we cover this scenario in Gitversion itself. Please check https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildAgents/GitHubActions.cs#L36

**Comment by RLittlesII** [comment]
@arturcic 

I went back and added 0.9.3 to this [build](https://github.com/RLittlesII/ReactiveUI.Showroom/runs/717345041?check_suite_focus=true) and it fails.

Previous [builds](https://github.com/RLittlesII/ReactiveUI.Showroom/runs/628357313?check_suite_focus=true) using the code directly from the branch this PR came from pass.

So I am not 100% sure what's going on.  I know this PR resolves a real issue I am seeing.  I don't mind continuing to use the forked version, we just figured we wouldn't be the only consumers who would face this issue.

**Comment by arturcic** [comment]
> @arturcic 
> 
> I went back and added 0.9.3 to this [build](https://github.com/RLittlesII/ReactiveUI.Showroom/runs/717345041?check_suite_focus=true) and it fails.
> 
> Previous [builds](https://github.com/RLittlesII/ReactiveUI.Showroom/runs/628357313?check_suite_focus=true) using the code directly from the branch this PR came from pass.
> 
> So I am not 100% sure what's going on.  I know this PR resolves a real issue I am seeing.  I don't mind continuing to use the forked version, we just figured we wouldn't be the only consumers who would face this issue.

I will have a look on the logs, thanks for sharing

**Comment by arturcic** [comment]
thank you so much for your contributions 👍

**Comment by david-driscoll** [comment]
🎉

**Pull request merged**
